FROM danteev/texlive

# Update apt cache and install required packages
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zsh \
    build-essential \
    libssl-dev \
    libffi-dev && \
    apt-get clean
